name: Outlier Energy
favicon: null
layout_spectrum: 0.860499074915424
typography_spectrum: 0.7049279280472547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dbdbdb'
    - '#9e9e9e'
    - '#747474'
    - '#262626'
  brandStrength: 0.044161097379401326
  lightness: 0.3795589762739837
  saturation: 0.24671245063655078
  rhythmicContrast: 0.17937588738277555
purpose: []
